name: Create Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        env:
          CI: ""
        run: |
          pushd app
          npm run all
          popd

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: gh-pages
          build_dir: app/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
